const axios = require('axios');
const config = require('../config');

const { spotify } = config;

const savePlaylistToSpotify = async (spotifyId, { tracks, name, public }) => {
  try {
    if (!tracks || tracks.length <= 0) {
      throw new Error('No tracks found');
    }

    const playlist = await axios.post(`${spotify.API_URL}/users/${spotifyId}/playlists`, {
      name: name || 'New playlist generated by Findify',
      public: public || false,
    });

    const uris = tracks.map((track) => track.uri);
    await axios.post(`${spotify.API_URL}/playlists/${playlist.data.id}/tracks?uris=${uris.toString()}`);
    const getPlaylist = await axios.get(`${spotify.API_URL}/playlists/${playlist.data.id}`);
    return getPlaylist;
  }
  catch (error) {
    throw error;
  }
}

module.exports = {
  savePlaylistToSpotify,
}